In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("globalAirQuality.csv")

In [4]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [6]:
# HOW TO SELECT COLUMN?
df["city"]

# HOW TO SELECT MULTIPLE COLUMN
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

loc --> selects on the basis of label
iloc --> selects on the basis of index

In [ ]:
# How to select ROWS?
df.loc[0]
df.loc[0:2]  #start_index(inclusive) : end_index(inclusive)

df.iloc[0]
df.iloc[0:2]  #start_index(inclusive) : end_index(exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [ ]:
# How to select rows and columns?

df.loc[0:2, "city"]


# 3 Different methods to print same thing
df.loc[0:2, ["country", "city", "latitude", "longitude"]]
df.iloc[0:3, [1,2,3,4]]
df.iloc[0:3, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [18]:
# How to select single scalar value? (at,iat)

df.at[0, 'city']
df.iat[0, 2]

'New York'

FILTERING DATA

In [34]:
df[(df['country'] == "IN") & (df['aqi'] > 180)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6641,2025-11-11 11:25:17.554219,IN,Mumbai,19.076,72.878,37.509,80.830,73.015,6.403,60.263,0.890,182,12.845,73.544,2.302
6747,2025-11-15 21:25:17.554219,IN,Mumbai,19.076,72.878,62.908,19.589,77.649,7.903,65.652,0.919,194,32.153,53.831,1.480
6783,2025-11-17 09:25:17.554219,IN,Mumbai,19.076,72.878,95.929,61.409,48.361,7.268,37.606,1.331,191,37.271,83.946,6.947
6954,2025-11-09 12:25:17.554219,IN,Delhi,28.704,77.102,94.626,65.452,25.394,10.327,41.224,0.857,189,10.302,71.682,3.934
7024,2025-11-12 10:25:17.554219,IN,Delhi,28.704,77.102,44.382,45.774,78.190,4.611,5.395,0.991,195,34.274,49.015,3.470
7178,2025-11-18 20:25:17.554219,IN,Delhi,28.704,77.102,18.817,52.704,72.507,7.433,59.090,0.655,181,18.714,60.559,7.946
7678,2025-11-09 16:25:17.554219,IN,Kolkata,22.573,88.364,91.538,46.013,24.842,3.966,75.040,1.273,183,19.667,52.976,3.175
8175,2025-11-15 09:25:17.554219,IN,Chennai,13.083,80.271,51.849,52.131,72.888,4.911,61.358,0.892,182,22.067,49.866,0.854

In [38]:
df[df['aqi'] > 200][['city', 'country','aqi']]

           city country  aqi
745      London      GB  214
8941      Osaka      JP  204
12956  Auckland      NZ  225
14555    Manila      PH  206
17458  Helsinki      FI  202
17529  Helsinki      FI  231
17815    Zurich      CH  203

FILTERING DATA USING QUERY:-

query() makes filtering look like SQL and cleaner.

In [45]:
# Expression as a string → Conditions are written inside quotes (e.g., "age > 25")
df.query('aqi > 200')

# Column based reference → Directly use column names without df['col'] (e.g., age > 25)

# Backticks (`) → Use when column names have spaces/special characters (e.g., `total marks` > 50)

# Operators → Supports &, |, ~, >, <, >=, <=, == for filtering conditions
df.query('temperature < 30 & aqi > 200')

# @ for Python variables → Use @ to access external variables inside query (e.g., age > @x)
Aqi = 200
df.query('aqi > @Aqi')

# Chained comparisons → Multiple conditions can be written cleanly (e.g., 20 < age < 30)
df.query('temperature < 30 & aqi > 200')[['city', 'country']]

           city country
745      London      GB
8941      Osaka      JP
12956  Auckland      NZ
14555    Manila      PH
17529  Helsinki      FI
17815    Zurich      CH

CLEANING DATA

How to handle missing values?